### ISSUE TITLE
esp8266 d1_mini not work ( need logger off)

### ISSUE THREAD

**Issue by techmike78** [pedobry/esphome_toshiba_suzumi#3]
I ran into a problem with your component working on Wemos D1 mini (esp8266). All connections were made with high quality and were working, but the air conditioner did not respond to commands from their ESPHome or HA, it worked from the remote control.
The problem turned out to be that it was necessary to turn off logging in uart:
logger:
   baud_rate: 0

Add this please to the description of the config for esp8266 and you can specify it in the text of the article. This will save a lot of time.

**Comment by pedobry** [comment]
My example config use pins 13 and 15 (SW UART) to avoid conflict with HW UART on pins 1 and 3. Which pins you use ?

**Comment by techmike78** [comment]
Now checking the work from HA, I noticed that the component does not receive commands from the air conditioner. For example, the air conditioner was turned off, I turn it on from the remote control, it turns on, but this is not visible in the component and HA.

**Comment by techmike78** [comment]
> My example config use pins 13 and 15 (SW UART) to avoid conflict with HW UART on pins 1 and 3. Which pins you use ?

How is the air conditioner controlled through the component and how does the air conditioner itself give its status to it?

**Comment by techmike78** [comment]
> My example config use pins 13 and 15 (SW UART) to avoid conflict with HW UART on pins 1 and 3. Which pins you use ?

soldered like you have, but with the GPIO15 connected, the esp8266 itself does not boot or flash.

**Comment by pedobry** [comment]
> > My example config use pins 13 and 15 (SW UART) to avoid conflict with HW UART on pins 1 and 3. Which pins you use ?
> 
> How is the air conditioner controlled through the component and how does the air conditioner itself give its status to it?

The serial communication over UART is bi-directional. When you make some change in HA, it's sent over serial to the AC unit. When some action is done via IR remote, the AC unit send a message over serial line and it's reflected in HA.

**Comment by techmike78** [comment]
> 

I forgot about the features of loading esp8266 and the state of the GPIO. I soldered GPIO15 to GPIO12 and it worked.
Sorry for wasting time.
Please describe my case on the main page so that you don't make these mistakes.
