### ISSUE TITLE
Question about HW

### ISSUE THREAD

**Issue by Volcano0** [pedobry/esphome_toshiba_suzumi#5]
I had the HW build as desrcibe on https://github.com/toremick/shorai-esp32.
But after the MQTT upgrade it doesn't work (to be precise I can change the AC params, but I cannot run it nor turn off).
Can I use the HW and upload ESPHome SW into it ?
Will it work or I have to build a dedicated HW with logic level shifters ?

**Comment by Volcano0** [comment]
I know the answer - the HW described here https://github.com/toremick/shorai-esp32 does work with Toshiba Shorai HVAC perfectly.

**Comment by pedobry** [comment]
Yes. As described in readme, you can use simpler level shifters or Toremic’s adapter. It’s HW and SW compatible.
