### ISSUE TITLE
MCC-1570-11 - question

### ISSUE THREAD

**Issue by 111lisu** [pedobry/esphome_toshiba_suzumi#8]
I have a question, what disc was it tested with? Because in MCC-1570 I have 12V power supply and higher levels on RX/TX, but I don't know if I have the right pin description?

![TccLink2](https://github.com/pedobry/esphome_toshiba_suzumi/assets/33672141/cbb87df6-526c-47a9-8c6d-8e5c8d334361)
![TccLink1](https://github.com/pedobry/esphome_toshiba_suzumi/assets/33672141/cc0dba35-6b5d-43c1-a06e-7fabc5ff61a0)

**Comment by pedobry** [comment]
The board must have a connector named CN22 to connect original wifi adapter. Supported are only units which have RB-N105S-G adapter as an option:

- Seiya RAS-B24 J2KVG-E
- Suzumi Plus RAS-B18, B22 a B24 PKVSG-E
- Shorai Premium RAS-B18, B22 a B24 J2KVRG-E
- Daiseikai 9 RAS-B10, B13 a B16 PKVPG-E
- Shorai Edge RAS-B07, B10, B13, B16, B18, B22 a B24 J2KVSG-E
- Seiya RAS-B10, B13, B16 a B18 J2KVG-E
- Suzumi Plus RAS-B10, B13 a B16 PKVSG-E
- Shorai Premium RAS-B10, B13 a B16 J2KVRG-E

**Comment by 111lisu** [comment]
thx
